Show due date main page
COSC310-Team12/ToDoList pull request #25
Opened 2022-10-30 21:21 UTC by te-sa

Showing the due date in a TextView under the Checkbox now, default is "Due date: none"

2022-10-30 22:05 UTC, justino599 commented on app/src/main/res/layout/todo_item.xml
> +        android:layout_marginStart="20dp"
android:layout_marginStart="62dp"

2022-10-30 22:10 UTC, justino599 commented on app/src/main/res/layout/todo_item.xml
> +        android:layout_marginStart="20dp"
android:layout_marginTop="8dp"

2022-10-30 22:18 UTC, justino599 commented on app/src/main/java/com/example/todolist/ToDoAdapter.java
> +        String pattern = "MM-dd-yyyy";
String pattern = "EEE, MMM dd";

2022-10-30 22:18 UTC, justino599 requested changes
I suggested a couple of layout changes, up to you if you think it looks better with them

2022-10-31 03:27 UTC, te-sa commented
I implemented the layout changes you suggested, I think they definitely improved things

2022-10-31 16:10 UTC, justino599 approved these changes

2022-10-31 16:40 UTC, merged